#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := bulbs

# Add your additional component directory
EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/MeshDirectedDiffusion

include $(IDF_PATH)/make/project.mk

